In [17]:
from openbb import obb
obb.user.preferences.output_type = "dataframe"

In [18]:
data = obb.equity.price.historical("SPY",provider="yfinance")

In [19]:
print(data)

                  open        high         low       close     volume  \
date
2023-08-24  444.690002  445.220001  436.859985  436.890015   88517300
2023-08-25  438.679993  441.299988  435.000000  439.970001  102325100
2023-08-28  442.239990  443.399994  439.970001  442.760010   61595400
2023-08-29  442.649994  449.450012  442.459991  449.160004   83081900
2023-08-30  449.510010  451.670013  448.779999  451.010010   69053900
...                ...         ...         ...         ...        ...
2024-08-19  554.729980  559.609985  553.859985  559.609985   39121800
2024-08-20  559.150024  560.840027  557.330017  558.700012   33732300
2024-08-21  559.770020  562.109985  554.729980  560.619995   41514600
2024-08-22  562.559998  563.179993  554.979980  556.219971   56121500
2024-08-23  559.530029  563.090027  557.289978  562.130005   50592900

            split_ratio  dividend  capital_gains
date
2023-08-24          0.0       0.0            0.0
2023-08-25          0.0       0.0            0.0
2023-08-28          0.0       0.0            0.0
2023-08-29          0.0       0.0            0.0
2023-08-30          0.0       0.0            0.0
...                 ...       ...            ...
2024-08-19          0.0       0.0            0.0
2024-08-20          0.0       0.0            0.0
2024-08-21          0.0       0.0            0.0
2024-08-22          0.0       0.0            0.0
2024-08-23          0.0       0.0            0.0

[252 rows x 8 columns]

In [7]:
obb.equity.fundamental.metrics("AAPL,MSFT",provider="yfinance")

,symbol,market_cap,pe_ratio,forward_pe,peg_ratio,peg_ratio_ttm,enterprise_to_ebitda,earnings_growth,earnings_growth_quarterly,revenue_per_share,...,price_to_book,enterprise_value,overall_risk,audit_risk,board_risk,compensation_risk,shareholder_rights_risk,beta,price_return_1y,currency
0,AAPL,3.448898e+12,34.474163,30.326202,3.02,2.2061,26.471,0.111,0.079,24.957,...,51.766315,3488409452544,1.0,6.0,1.0,2.0,1.0,1.244,0.258893,USD
1,MSFT,3.098017e+12,35.321186,27.366383,2.18,2.2478,24.108,0.097,0.097,32.986,...,11.540634,3120336994304,1.0,3.0,4.0,2.0,2.0,0.894,0.287581,USD

In [10]:
#compare industries based on valutation
obb.equity.compare.groups(group="industry",metric="valuation",provider="finviz")

,name,market_cap,performance_1D,forward_pe,eps_growth_past_5_years,eps_growth_next_5_years,sales_growth_past_5_years,volume,price_to_sales,price_to_book,price_to_cash,price_to_free_cash_flow,pe,peg
0,Pharmaceutical Retailers,9140000000,0.0263,5.33,-0.0546,0.0427,0.0366,18560000,0.06,0.66,11.18,400.80,NaN,NaN
1,Coking Coal,9640000000,0.0121,6.99,0.0588,0.0628,0.1532,2780000,0.91,1.57,6.67,9.12,7.86,1.25
2,Airlines,114930000000,0.0362,7.26,-0.0465,0.1572,0.2475,86950000,0.42,1.96,2.04,25.44,10.98,0.70
3,REIT - Mortgage,58020000000,0.0150,7.62,-0.2175,0.0315,0.3566,47610000,1.83,0.89,4.13,5.52,24.65,7.82
4,Marine Shipping,39010000000,0.0161,7.97,0.2128,0.0874,0.2475,17280000,1.29,1.09,6.04,9.58,7.01,0.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,REIT - Office,74240000000,0.0271,55.18,-0.2150,0.0032,0.0685,22600000,3.80,1.07,8.47,13.49,86.34,266.09
141,REIT - Healthcare Facilities,153640000000,0.0134,59.54,-0.1288,0.0530,0.1222,28690000,6.65,1.98,28.47,26.77,105.88,19.96
142,Shell Companies,25180000000,0.0007,127.60,0.4287,NaN,0.6926,15240000,21.66,1.94,36.87,100.87,49.59,NaN
143,Real Estate - Diversified,7570000000,0.0334,147.59,0.1832,0.1982,0.2136,511380,4.81,1.93,7.39,72.22,95.47,4.82
144,Infrastructure Operations,35080000000,0.0231,153.23,NaN,0.1425,0.0814,812030,3.36,7.65,8.64,33.86,38.33,2.69

In [13]:
#compare in technology based on performance
obb.equity.compare.groups(group="technology",metric="performance",provider="finviz")

,name,performance_1D,performance_1W,performance_1M,performance_3M,performance_6M,performance_1Y,performance_YTD,analyst_recommendation,volume,volume_average,volume_relative
0,Semiconductor Equipment & Materials,0.0105,-0.0127,0.0238,-0.0414,0.0127,0.3457,0.1991,1.69,22480000,28580000,0.79
1,Software - Infrastructure,0.0045,0.0017,0.0143,0.0077,0.0266,0.2470,0.0987,1.51,328540000,360830000,0.91
2,Computer Hardware,0.0143,0.0032,0.0280,-0.0539,0.1733,0.6566,0.4133,1.99,51840000,76650000,0.68
3,Consumer Electronics,0.0104,0.0042,0.0438,0.2111,0.2347,0.2469,0.1699,1.87,46090000,78360000,0.59
4,Software - Application,0.0108,0.0121,0.0272,0.0171,-0.0346,0.2385,0.0316,1.73,354780000,360150000,0.99
5,Information Technology Services,0.0075,0.0170,0.0283,0.1164,0.0092,0.2131,0.0879,2.18,65650000,86700000,0.76
6,Semiconductors,0.0362,0.0214,0.0931,0.1293,0.3349,0.9240,0.6904,1.50,685920000,678320000,1.01
7,Communication Equipment,0.0172,0.0296,0.0861,0.1322,0.1542,0.0832,0.1280,2.31,122790000,134090000,0.92
8,Electronic Components,0.0163,0.0326,0.0266,0.0286,0.1613,0.2860,0.2209,1.93,132050000,70130000,1.88
9,Electronics & Computer Distribution,0.0218,0.0336,0.0475,0.0037,0.1590,0.2048,0.1318,2.54,2110000,2450000,0.86
10,Scientific & Technical Instruments,0.0144,0.0502,0.0391,0.0367,0.0546,0.1943,0.1099,2.13,18620000,29860000,0.62
11,Solar,0.0659,0.0503,0.0325,-0.0573,0.0590,-0.1961,-0.1035,1.85,89140000,144680000,0.62

In [16]:
# compare sector overview
obb.equity.compare.groups(group="sector",metric="overview",provider="finviz")

,name,stocks,market_cap,performance_1D,dividend_yield,pe,forward_pe,peg,float_short,volume
0,Consumer Defensive,248,4106870000000,0.0048,0.0256,26.13,19.67,3.15,0.0166,301950000
1,Utilities,113,1533610000000,0.0058,0.0315,20.39,16.15,2.57,0.0193,167130000
2,Healthcare,1184,8636400000000,0.0071,0.0143,40.02,19.72,2.28,0.0449,1100000000
3,Communication Services,260,7835260000000,0.0082,0.0087,24.07,17.80,1.35,0.0253,500640000
4,Financial,947,11139180000000,0.0140,0.0204,16.06,13.91,1.52,0.0126,934410000
5,Industrials,652,5724440000000,0.0141,0.0142,25.68,19.80,2.27,0.0420,788110000
6,Energy,251,3528600000000,0.0161,0.0451,11.95,10.10,1.85,0.0263,419090000
7,Basic Materials,273,2089010000000,0.0164,0.0233,23.15,14.57,2.47,0.0204,374490000
8,Consumer Cyclical,574,7403710000000,0.0168,0.0097,23.53,18.45,1.41,0.0470,1460000000
9,Technology,790,20102680000000,0.0175,0.0067,41.71,26.01,2.11,0.0266,1920000000
10,Real Estate,264,1673960000000,0.0207,0.0364,39.88,32.24,5.56,0.0443,333060000